# Development stage
FROM node:18-alpine

# Set workdir
WORKDIR /app

# Install dependencies first for better caching
COPY app/package*.json ./

# Install dependencies with development tools
RUN npm ci --prefer-offline --no-audit --progress=false

# Copy the rest of the app
COPY app .

# Set environment variables
ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000

# Expose Nuxt default port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]