# Development stage
FROM node:18

RUN apt-get update && apt-get install -y wget gnupg curl
# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Install MongoDB Database Tools
RUN wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian92-x86_64-100.3.1.deb && \
	apt install -y ./mongodb-database-tools-*.deb && \
	rm -f mongodb-database-tools-*.deb

# Install mongosh
RUN curl -fsSL https://pgp.mongodb.com/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-6.0.gpg && \
	echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main" \
		> /etc/apt/sources.list.d/mongodb-org-6.0.list && \
	apt-get update && \
	apt-get install -y mongodb-mongosh && \
	rm -rf /var/lib/apt/lists/*

# Set workdir
WORKDIR /app

# Install dependencies first for better caching
COPY app/pnpm-lock.yaml app/package.json ./

# Install dependencies with development tools
RUN pnpm i --frozen-lockfile

# Copy the rest of the app
COPY app .

# Set environment variables
ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000

# Expose Nuxt default port
EXPOSE 3000

# Command to run the application
CMD ["pnpm", "run", "dev"]