name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./app/package-lock.json  # important!

    - name: Install dependencies
      run: npm install
      working-directory: ./app

    - name: Run tests
      run: npm run test
      working-directory: ./app
